name: smart_shop
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.6
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_iconly: ^1.0.2
  google_nav_bar: ^5.0.6
  ionicons: ^0.2.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.2
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  image_picker: ^1.0.4
  uuid: ^4.1.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.1.5
  firebase_database: ^11.3.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  country_flags: ^2.2.0
  intl_phone_field: ^3.2.0
  lottie: ^2.7.0
  url_launcher: ^6.3.1
  curved_navigation_bar: ^1.0.3
  share_plus: ^7.2.1
  readmore: ^2.2.0
  gap: ^3.0.1
  get_it: ^8.0.3
  get: ^4.6.6
  # change_app_package_name: ^1.1.0

# icons_launcher:
#   image_path: "assets/AppLogo.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bag/
    - assets/categories/
    - assets/Lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

