name: salla
description: SALLA IS AN E_COMMERCE APPLICATION
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_launcher: ^2.1.6
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_iconly: ^1.0.2
  google_nav_bar: ^5.0.6
  ionicons: ^0.2.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.2
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  image_picker: ^1.0.4
  uuid: ^4.1.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.0
  google_sign_in: ^6.1.5
  firebase_database: ^11.3.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  country_flags: ^2.2.0
  intl_phone_field: ^3.2.0
  lottie: ^2.7.0
  url_launcher: ^6.3.1
  curved_navigation_bar: ^1.0.3
  share_plus: ^7.2.1
  readmore: ^2.2.0
  gap: ^3.0.1
  get_it: ^8.0.3
  get: ^4.6.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_launcher_icons: ^0.14.3
  auto_size_text: ^3.0.0
  timelines_plus: ^1.0.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/salla-logo.png"
  min_sdk_android: 21

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/banners/
    - assets/images/bag/
    - assets/images/auth/
    - assets/categories/
    - assets/images/category/
    - assets/images/logo/
    - assets/Lottie/
    - assets/svg/
    - assets/svg/nav/
    - assets/svg/brand/
    - assets/svg/profile/
    - assets/svg/global/

  fonts:
    - family: 'urbanist'
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/urbanist/Urbanist-VariableFont_wght.ttf
    - family: 'Roboto'
      fonts:
        - asset: assets/fonts/Roboto_Condensed/static/RobotoCondensed-SemiBold.ttf


